version: '3'

volumes:
  static-files:
  songs-cache:
    # If you want to access downloaded files on your host system,
    # uncomment the following lines and choose a folder.
    #driver_opts:
    #  type: 'none'
    #  o: 'bind'
    #  device: '/path/to/folder/'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=raveberry
      - POSTGRES_USER=raveberry
      - POSTGRES_PASSWORD=raveberry
    restart: always
  redis:
    image: redis
    restart: always
  mopidy:
    image: raveberry/raveberry-mopidy
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - songs-cache:/Music/raveberry
      # Comment this line if pulse does not work.
      - "/run/user/${UID:-1000}/pulse:/run/user/105/pulse"
      # If you want to use spotify, 
      # uncomment this line with a path to a config file containing the spotify credentials
      # - /path/to/mopidy.conf:/config/mopidy.conf
    restart: always
    # Use these three lines to use alsa if pulse is not working.
    #user: root
    #devices:
    #  - "/dev/snd:/dev/snd"
  daphne:
    image: raveberry/raveberry
    environment:
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:-admin}"
      MOD_PASSWORD: "${MOD_PASSWORD:-mod}"
      PAD_PASSWORD: "${PAD_PASSWORD:-pad}"
      DOCKER: 1
    expose:
      - 9000
    volumes:
      - static-files:/opt/raveberry/static
      - songs-cache:/Music/raveberry
    depends_on:
      - db
      - redis
      - mopidy
    restart: always
  nginx:
    image: raveberry/raveberry-nginx
    ports:
      - "80:80"
    volumes:
      - static-files:/usr/share/nginx/static
    depends_on:
      - daphne
    restart: always
